### ISSUE TITLE
How to control wigglyness of fitted curve (using Matern5/2 kernel)

### ISSUE THREAD

**Issue by las-matthew-bennett** [CollinErickson/GauPro#2]
Hello, 

I'm trying to use your package to fit a model to some data (28 points) and I'm wondering if there's an argument to the `gpkm()` or the `Matern52$new()` functions that would force the fitted curve to be smoother?

I can't find anything in the docs, but I see from other googling that some parameters do indeed control the smoothness of the curve? 

Any help would be appreciated!
Thanks

**Comment by CollinErickson** [comment]
Sorry for not seeing this until now. GitHub never sent me emails for issues or pull requests, which I just found out recently. You probably don't care anymore, but I'll answer anyway.

First of all, I would switch to using `k_Matern52` instead of `Matern52$new()`, since RStudio is better at giving hints for functions than R6 objects.

For this, you would want to change the values of `beta_lower` and `beta_upper` to constrain it so that it is forced to have the wiggliness that you want. To make it more wigglier, you would want larger values of `beta`. So if it's already at `beta_upper`, then increase that so it can get more wigglier. If it's not near `beta_upper`, then you can force it in that direction by increasing `beta_lower` to be higher than the value of `beta` you are getting.

Alternatively, you could leave the parameters but scale the dimensions (preprocess your X matrix).
